Repository systemli/userli, pull requests merged in 2024-09, with the labels that each got.

#639 feat: Add user API endpoint to get list of aliases
  .env
  .env.test
  .github/workflows/integration.yml
  .github/workflows/psalm.yml
  CHANGELOG.md
  config/packages/security.yaml
  src/Controller/RoundcubeController.php
  src/DataFixtures/LoadAliasData.php
  src/DataFixtures/LoadRandomAliasData.php
  src/DataFixtures/LoadUserData.php
  tests/Controller/KeycloakControllerTest.php
  tests/Controller/RoundcubeControllerTest.php
Labels: enhancement

#640 👷 Set a explicit version for sonarcloud github action
  .github/workflows/integration.yml
Labels: dependencies

#642 👷 Upgrade Database Versions for Development
  .github/workflows/integration.yml
  docker-compose.yml
Labels: dependencies

#646 Show email and domain filters per default in admin user list
  src/Admin/UserAdmin.php
Labels: bug

#647 Prepare for 3.9.1 release
  CHANGELOG.md
Labels: enhancement
