Repository systemli/userli, pull requests merged in 2025-04, with the labels that each got.

#758 Change booleans in docker compose env vars to integers
  docker-compose.yml
Labels: bug

#759 Reset two-factor authentication with recovery process
  default_translations/de/messages.de.yml
  default_translations/en/messages.en.yml
  default_translations/fr/messages.fr.yml
  default_translations/gsw/messages.gsw.yml
  default_translations/nb/messages.nb.yml
  default_translations/pt/messages.pt.yml
  src/Controller/RecoveryController.php
  templates/Recovery/reset_password.html.twig
Labels: bug

#700 🔥 Remove UsersCheckPasswordCommand
  config/services.yaml
  src/Command/UsersCheckPasswordCommand.php
  src/Helper/FileDescriptorReader.php
  tests/Command/UsersCheckPasswordCommandTest.php
Labels: enhancement

#762 refactor: Add abstract UsersBaseCommand class
  config/services.yaml
  features/mailCryptCommand.feature
  features/quotaCommand.feature
  features/voucherCreateCommand.feature
  src/Command/AbstractUsersCommand.php
  src/Command/ReservedNamesImportCommand.php
  src/Command/UsersDeleteCommand.php
  src/Command/UsersListCommand.php
  src/Command/UsersMailCryptCommand.php
  src/Command/UsersQuotaCommand.php
  src/Command/UsersResetCommand.php
  src/Command/UsersRestoreCommand.php
  src/Command/VoucherCountCommand.php
  src/Command/VoucherCreateCommand.php
  src/Handler/UserRestoreHandler.php
  tests/Command/UsersRestoreCommandTest.php
  tests/Handler/UserRestoreHandlerTest.php
Labels: technical dept

#765 Call webhook URLs on user created/deleted events
  .env
  CHANGELOG.md
  config/services.yaml
  src/Event/Events.php
  src/Event/UserCreatedEvent.php
  src/Event/UserDeletedEvent.php
  src/EventListener/UserCreatedListener.php
  src/EventListener/UserDeletedListener.php
  src/Handler/DeleteHandler.php
  src/Handler/RegistrationHandler.php
  src/Handler/UserRestoreHandler.php
  src/Handler/WebhookHandler.php
  tests/EventListener/UserCreatedListenerTest.php
  tests/EventListener/UserDeletedListenerTest.php
  tests/Handler/DeleteHandlerTest.php
  tests/Handler/RegistrationHandlerTest.php
  tests/Handler/UserRestoreHandlerTest.php
  tests/Handler/WebhookHandlerTest.php
Labels: enhancement

#771 Remove remnants of dangerous/error-prone mailcrypt migration script
  bin/mailcrypt-encrypt-maildir
  docs/features/mail_crypt.md
Labels: bug

#770 Fix displaying recovery token in user restore command
  src/Command/UsersRestoreCommand.php
  tests/Command/UsersRestoreCommandTest.php
  tests/Handler/UserRestoreHandlerTest.php
Labels: bug

#772 Add lowercase validator and use it for email and name trait
  default_translations/de/validators.de.yml
  default_translations/en/validators.en.yml
  src/Creator/DomainCreator.php
  src/Traits/EmailTrait.php
  src/Traits/NameTrait.php
  src/Validator/Constraints/Lowercase.php
  src/Validator/Constraints/LowercaseValidator.php
  tests/Validator/Constraints/LowercaseValidatorTest.php
Labels: bug
